between random: 121346323
between random: 121346318
between random: 121346323
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
timeout: the monitored command dumped core
Aborted
output directory: temp/2125
implementation directory: /quic/quant/Debug/bin/
implementation command: ./server -d . -c /QUIC-Ivy/doc/examples/quic/leaf_cert.pem -k /QUIC-Ivy/doc/examples/quic/leaf_cert.key -p 4443 -t 3600 -v 5
../quic_server_test_max (0) ...
implementation command: ['./server', '-d', '.', '-c', '/QUIC-Ivy/doc/examples/quic/leaf_cert.pem', '-k', '/QUIC-Ivy/doc/examples/quic/leaf_cert.key', '-p', '4443', '-t', '3600', '-v', '5']
quic_process pid: 30870
timeout 100 ./build/quic_server_test_max seed=0 the_cid=0 server_cid=1 client_port=4987 client_port_alt=4988
client return code: 134
FAIL
error: 1 tests(s) failed
