bind failed: Address already in use
bind failed: Address already in use
output directory: temp/1132
implementation directory: /home/chris/TVOQE_UPGRADE_27/quic/aioquic/
implementation command: python3 examples/http3_server.py --quic-log /home/chris/qlog_aiquic2 --certificate /home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_cert.pem --private-key /home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_key.pem  -v --host 127.0.0.1 --port 4443 -l /home/chris/secret.log
../quic_server_test_unkown (0) ...
implementation command: ['python3', 'examples/http3_server.py', '--quic-log', '/home/chris/qlog_aiquic2', '--certificate', '/home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_cert.pem', '--private-key', '/home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_key.pem', '-v', '--host', '127.0.0.1', '--port', '4443', '-l', '/home/chris/secret.log']
quic_process pid: 7971
timeout 100 ./build/quic_server_test_unkown seed=945 the_cid=0 server_cid=1 client_port=4987 client_port_alt=4988
client return code: 1
FAIL
../quic_server_test_unkown_tp (0) ...
implementation command: ['python3', 'examples/http3_server.py', '--quic-log', '/home/chris/qlog_aiquic2', '--certificate', '/home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_cert.pem', '--private-key', '/home/chris/TVOQE_UPGRADE_27/quic/aioquic/tests/ssl_key.pem', '-v', '--host', '127.0.0.1', '--port', '4443', '-l', '/home/chris/secret.log']
quic_process pid: 8011
timeout 100 ./build/quic_server_test_unkown_tp seed=402 the_cid=0 server_cid=1 client_port=4987 client_port_alt=4988
client return code: 1
FAIL
error: 2 tests(s) failed
